columns:
  - groups:
      - name: Performance testing
        skills:
          - name: NeoLoad
            level: 9
          - name: Apache JMeter
            level: 6
      - name: Test Automation & Frameworks
        skills:
          - name: Selenium Webdriver
            level: 8
          - name: Jest
            level: 6
      - name: Monitoring Systems - APM
        skills:
          - name: Dynatrace
            level: 7
          - name: Sentry
            level: 7
          - name: Prometheus
            level: 5
          - name: Elastic APM
            level: 5
          - name: Grafana
            level: 5
      - name: Programming Languages
        skills:
          - name: Javascirpt
            level: 8
          - name: TypeScript
            level: 7
          - name: Golang
            level: 6
          - name: C
            level: 7
          - name: C++
            level: 6
          - name: C#
            level: 6
          - name: HTML5
            level: 8
          - name: CSS3
            level: 9
  - groups:
      - name: Software Frameworks & Libraries
        skills:
          - name: Angular
            level: 8
          - name: RxJS
            level: 9
          - name: Electron
            level: 8
          - name: Sass
            level: 8
          - name: .NET Core
            level: 5
          - name: Entity Framework
            level: 6
      - name: Version Control
        skills:
          - name: Git
            level: 8
          - name: GitHub
            level: 7
          - name: GitLab
            level: 9
          - name: Azure DevOps
            level: 8
      - name: Databases
        skills:
          - name: PostgreSQL
            level: 6
          - name: MySQL
            level: 5
      - name: Web Server
        skills:
          - name: NGINX
            level: 7
  - groups:
      - name: Operating Systems
        skills:
          - name: Windows 10
            level: 9
          - name: macOS
            level: 9
          - name: Arch Linux
            level: 6
          - name: Ubuntu
            level: 6
          - name: RHEL
            level: 5
      - name: Containerization
        skills:
          - name: Docker
            level: 7
          - name: Kubernetes
            level: 7
          - name: k3s
            level: 6
          - name: buildah
            level: 5
          - name: podman
            level: 5
      - name: DevOps
        skills:
          - name: GitLab CI
            level: 7
          - name: Azure Pipelines
            level: 7
          - name: Keptn
            level: 8
      - name: Cloud Hosting
        skills:
          - name: Microsoft Azure
            level: 7
          - name: Linode
            level: 5
  - groups:
    - name: Issue Tracking
      skills:
        - name: Atlassian Jira
          level: 8
        - name: GitLab Issues
          level: 7
        - name: GitHub Issues
          level: 7
    - name: Other tools
      skills:
        - name: Visual Studio Code
          level: 8
        - name: Affinity Designer
          level: 10
        - name: Affinity Photo
          level: 8
        - name: Beyond Compare
          level: 9
    - name: Languages
      skills:
        - name: German (native)
          level: 10
        - name: English
          level: 9
    - name: Daily Usage
      skills:
        - name: Microsoft Outlook
          level: -1
        - name: Microsoft Teams
          level: -1
        - name: Zoom
          level: -1
        - name: Skype
          level: -1
        - name: Slack
          level: -1
        - name: ZSH ; )
          level: -1