settings:
    isLandscape: true
columns:
    - groups:
        - name: Programming Languages
          skills:
            - name: Javascirpt
              level: 9
            - name: TypeScript
              level: 8
            - name: Golang
              level: 8
            - name: C
              level: 7
            - name: C++
              level: 6
            - name: C#
              level: 6
            - name: HTML5
              level: 10
            - name: CSS3
              level: 10
        - name: DevOps
          skills:
            - name: GitLab CI
              level: 10
            - name: Azure Pipelines
              level: 7
            - name: Keptn
              level: 8
    - groups:
        - name: Issue Tracking
          skills:
            - name: Atlassian Jira
              level: 10
            - name: GitLab Issues
              level: 7
            - name: GitHub Issues
              level: 7
